// Generated by CoffeeScript 2.7.0

//     Constants

export var X = 0;

export var Y = 1;

export var ARENA_WIDTH = 1000;

export var TAU = Math.PI * 2;

export var RAD_TO_DEG = 57.2957795131; // 360 / (PI * 2)

export var DEG_TO_RAD = 0.01745329252;

//# sourceMappingURL=constants.js.map
